services:
  nginx:
    container_name: nginx
    hostname: backend
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    networks:
      - Inception
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://scarpent.42.fr || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 5

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    networks:
      - Inception
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://scarpent.42.fr:9000 || exit 0"]
      interval: 2s
      timeout: 10s
      retries: 5

  mariadb:
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    networks:
      - Inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h scarpent.42.fr -u root -p${MDB_ROOT_PWD} || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 5

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/dolphin/data/mysql
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/dolphin/data/wordpress
      o: bind

networks:
  Inception:
    name: Inception
    driver: bridge